apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-service
  labels:
    run: account-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: account-service
    spec:
      containers:
      - name: account-service
        image: headless-crawler/xpath_tool
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP